// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.2.0.0
//      Runtime Version:2.0.50727.3603
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace MavenThought.MediaLibrary.Acceptance.Tests.Features
{
    using TechTalk.SpecFlow;
    
    
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Browse Movies")]
    public partial class BrowseMoviesFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "BrowseMovies.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Browse Movies", "As a User\r\nI want to Browse Movies\r\nSo I can see the contents of the library", ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Browse available movies")]
        public virtual void BrowseAvailableMovies()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Browse available movies", ((string[])(null)));
#line 6
 this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "title"});
            table1.AddRow(new string[] {
                        "Blazing Saddles"});
            table1.AddRow(new string[] {
                        "Space Balls"});
#line 7
  testRunner.Given("I have the following movies:", ((string)(null)), table1);
#line 11
  testRunner.When("I go to Movies");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "title"});
            table2.AddRow(new string[] {
                        "Blazing Saddles"});
            table2.AddRow(new string[] {
                        "Space Balls"});
#line 12
  testRunner.Then("I should see in the listing:", ((string)(null)), table2);
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Browse empty library")]
        public virtual void BrowseEmptyLibrary()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Browse empty library", ((string[])(null)));
#line 17
 this.ScenarioSetup(scenarioInfo);
#line 18
  testRunner.Given("I have no movies");
#line 19
  testRunner.When("I go to Movies");
#line 20
  testRunner.Then("I should see the message Sorry no movies available!");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
