//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Model", "FK_login_users", "users", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MediaLibrary.Core.Model.ADOEF.User), "login", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MediaLibrary.Core.Model.ADOEF.LoginIdentification))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Model", "FK_media_search_engines", "search_engines", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MediaLibrary.Core.Model.ADOEF.SearchEngine), "media", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MediaLibrary.Core.Model.ADOEF.Media))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Model", "FK_reviews_media", "media", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MediaLibrary.Core.Model.ADOEF.Media), "reviews", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MediaLibrary.Core.Model.ADOEF.Review))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Model", "FK_users_media_media", "media", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MediaLibrary.Core.Model.ADOEF.Media), "users_media", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MediaLibrary.Core.Model.ADOEF.UsersMedia))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Model", "FK_reviews_review_engines", "review_engines", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MediaLibrary.Core.Model.ADOEF.ReviewEngine), "reviews", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MediaLibrary.Core.Model.ADOEF.Review))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Model", "FK_users_media_users", "users", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MediaLibrary.Core.Model.ADOEF.User), "users_media", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MediaLibrary.Core.Model.ADOEF.UsersMedia))]

// Original file name:
// Generation date: 1/2/2009 8:57:08 PM
namespace MediaLibrary.Core.Model.ADOEF
{
    
    /// <summary>
    /// There are no comments for MediaEntities in the schema.
    /// </summary>
    public partial class MediaEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new MediaEntities object using the connection string found in the 'MediaEntities' section of the application configuration file.
        /// </summary>
        public MediaEntities() : 
                base("name=MediaEntities", "MediaEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new MediaEntities object.
        /// </summary>
        public MediaEntities(string connectionString) : 
                base(connectionString, "MediaEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new MediaEntities object.
        /// </summary>
        public MediaEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "MediaEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for LoginIds in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<LoginIdentification> LoginIds
        {
            get
            {
                if ((this._LoginIds == null))
                {
                    this._LoginIds = base.CreateQuery<LoginIdentification>("[LoginIds]");
                }
                return this._LoginIds;
            }
        }
        private global::System.Data.Objects.ObjectQuery<LoginIdentification> _LoginIds;
        /// <summary>
        /// There are no comments for Media in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Media> Media
        {
            get
            {
                if ((this._Media == null))
                {
                    this._Media = base.CreateQuery<Media>("[Media]");
                }
                return this._Media;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Media> _Media;
        /// <summary>
        /// There are no comments for ReviewEngines in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ReviewEngine> ReviewEngines
        {
            get
            {
                if ((this._ReviewEngines == null))
                {
                    this._ReviewEngines = base.CreateQuery<ReviewEngine>("[ReviewEngines]");
                }
                return this._ReviewEngines;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ReviewEngine> _ReviewEngines;
        /// <summary>
        /// There are no comments for Reviews in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Review> Reviews
        {
            get
            {
                if ((this._Reviews == null))
                {
                    this._Reviews = base.CreateQuery<Review>("[Reviews]");
                }
                return this._Reviews;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Review> _Reviews;
        /// <summary>
        /// There are no comments for SearchEngines in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<SearchEngine> SearchEngines
        {
            get
            {
                if ((this._SearchEngines == null))
                {
                    this._SearchEngines = base.CreateQuery<SearchEngine>("[SearchEngines]");
                }
                return this._SearchEngines;
            }
        }
        private global::System.Data.Objects.ObjectQuery<SearchEngine> _SearchEngines;
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<User> Users
        {
            get
            {
                if ((this._Users == null))
                {
                    this._Users = base.CreateQuery<User>("[Users]");
                }
                return this._Users;
            }
        }
        private global::System.Data.Objects.ObjectQuery<User> _Users;
        /// <summary>
        /// There are no comments for UsersMediaSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<UsersMedia> UsersMediaSet
        {
            get
            {
                if ((this._UsersMediaSet == null))
                {
                    this._UsersMediaSet = base.CreateQuery<UsersMedia>("[UsersMediaSet]");
                }
                return this._UsersMediaSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<UsersMedia> _UsersMediaSet;
        /// <summary>
        /// There are no comments for LoginIds in the schema.
        /// </summary>
        public void AddToLoginIds(LoginIdentification loginIdentification)
        {
            base.AddObject("LoginIds", loginIdentification);
        }
        /// <summary>
        /// There are no comments for Media in the schema.
        /// </summary>
        public void AddToMedia(Media media)
        {
            base.AddObject("Media", media);
        }
        /// <summary>
        /// There are no comments for ReviewEngines in the schema.
        /// </summary>
        public void AddToReviewEngines(ReviewEngine reviewEngine)
        {
            base.AddObject("ReviewEngines", reviewEngine);
        }
        /// <summary>
        /// There are no comments for Reviews in the schema.
        /// </summary>
        public void AddToReviews(Review review)
        {
            base.AddObject("Reviews", review);
        }
        /// <summary>
        /// There are no comments for SearchEngines in the schema.
        /// </summary>
        public void AddToSearchEngines(SearchEngine searchEngine)
        {
            base.AddObject("SearchEngines", searchEngine);
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
        /// <summary>
        /// There are no comments for UsersMediaSet in the schema.
        /// </summary>
        public void AddToUsersMediaSet(UsersMedia usersMedia)
        {
            base.AddObject("UsersMediaSet", usersMedia);
        }
    }
    /// <summary>
    /// There are no comments for Model.LoginIdentification in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Model", Name="LoginIdentification")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class LoginIdentification : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new LoginIdentification object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="loginName">Initial value of LoginName.</param>
        /// <param name="password">Initial value of Password.</param>
        public static LoginIdentification CreateLoginIdentification(int id, string loginName, string password)
        {
            LoginIdentification loginIdentification = new LoginIdentification();
            loginIdentification.Id = id;
            loginIdentification.LoginName = loginName;
            loginIdentification.Password = password;
            return loginIdentification;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property LoginName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginName
        {
            get
            {
                return this._LoginName;
            }
            set
            {
                this.OnLoginNameChanging(value);
                this.ReportPropertyChanging("LoginName");
                this._LoginName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("LoginName");
                this.OnLoginNameChanged();
            }
        }
        private string _LoginName;
        partial void OnLoginNameChanging(string value);
        partial void OnLoginNameChanged();
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this.ReportPropertyChanging("Password");
                this._Password = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Password");
                this.OnPasswordChanged();
            }
        }
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Model", "FK_login_users", "users")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public User User
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("Model.FK_login_users", "users").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("Model.FK_login_users", "users").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<User> UserReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("Model.FK_login_users", "users");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<User>("Model.FK_login_users", "users", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Model.Media in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Model", Name="Media")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Media : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Media object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="title">Initial value of Title.</param>
        /// <param name="releaseDate">Initial value of ReleaseDate.</param>
        /// <param name="addedDate">Initial value of AddedDate.</param>
        public static Media CreateMedia(int id, string title, global::System.DateTime releaseDate, global::System.DateTime addedDate)
        {
            Media media = new Media();
            media.Id = id;
            media.Title = title;
            media.ReleaseDate = releaseDate;
            media.AddedDate = addedDate;
            return media;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property ReleaseDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime ReleaseDate
        {
            get
            {
                return this._ReleaseDate;
            }
            set
            {
                this.OnReleaseDateChanging(value);
                this.ReportPropertyChanging("ReleaseDate");
                this._ReleaseDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ReleaseDate");
                this.OnReleaseDateChanged();
            }
        }
        private global::System.DateTime _ReleaseDate;
        partial void OnReleaseDateChanging(global::System.DateTime value);
        partial void OnReleaseDateChanged();
        /// <summary>
        /// There are no comments for Property AddedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime AddedDate
        {
            get
            {
                return this._AddedDate;
            }
            set
            {
                this.OnAddedDateChanging(value);
                this.ReportPropertyChanging("AddedDate");
                this._AddedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AddedDate");
                this.OnAddedDateChanged();
            }
        }
        private global::System.DateTime _AddedDate;
        partial void OnAddedDateChanging(global::System.DateTime value);
        partial void OnAddedDateChanged();
        /// <summary>
        /// There are no comments for SourceEngine in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Model", "FK_media_search_engines", "search_engines")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public SearchEngine SourceEngine
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SearchEngine>("Model.FK_media_search_engines", "search_engines").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SearchEngine>("Model.FK_media_search_engines", "search_engines").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for SourceEngine in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<SearchEngine> SourceEngineReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SearchEngine>("Model.FK_media_search_engines", "search_engines");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<SearchEngine>("Model.FK_media_search_engines", "search_engines", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for MediaReviews in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Model", "FK_reviews_media", "reviews")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Review> MediaReviews
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Review>("Model.FK_reviews_media", "reviews");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Review>("Model.FK_reviews_media", "reviews", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Model", "FK_users_media_media", "users_media")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public UsersMedia User
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<UsersMedia>("Model.FK_users_media_media", "users_media").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<UsersMedia>("Model.FK_users_media_media", "users_media").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<UsersMedia> UserReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<UsersMedia>("Model.FK_users_media_media", "users_media");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<UsersMedia>("Model.FK_users_media_media", "users_media", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Model.ReviewEngine in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Model", Name="ReviewEngine")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ReviewEngine : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ReviewEngine object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="title">Initial value of Title.</param>
        /// <param name="description">Initial value of Description.</param>
        public static ReviewEngine CreateReviewEngine(int id, string title, string description)
        {
            ReviewEngine reviewEngine = new ReviewEngine();
            reviewEngine.Id = id;
            reviewEngine.Title = title;
            reviewEngine.Description = description;
            return reviewEngine;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Reviews in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Model", "FK_reviews_review_engines", "reviews")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Review> Reviews
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Review>("Model.FK_reviews_review_engines", "reviews");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Review>("Model.FK_reviews_review_engines", "reviews", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Model.Review in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Model", Name="Review")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Review : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Review object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="reviewContent">Initial value of ReviewContent.</param>
        public static Review CreateReview(int id, string reviewContent)
        {
            Review review = new Review();
            review.Id = id;
            review.ReviewContent = reviewContent;
            return review;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property ReviewContent in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ReviewContent
        {
            get
            {
                return this._ReviewContent;
            }
            set
            {
                this.OnReviewContentChanging(value);
                this.ReportPropertyChanging("ReviewContent");
                this._ReviewContent = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ReviewContent");
                this.OnReviewContentChanged();
            }
        }
        private string _ReviewContent;
        partial void OnReviewContentChanging(string value);
        partial void OnReviewContentChanged();
        /// <summary>
        /// There are no comments for Media in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Model", "FK_reviews_media", "media")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Media Media
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Media>("Model.FK_reviews_media", "media").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Media>("Model.FK_reviews_media", "media").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Media in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Media> MediaReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Media>("Model.FK_reviews_media", "media");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Media>("Model.FK_reviews_media", "media", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Engine in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Model", "FK_reviews_review_engines", "review_engines")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public ReviewEngine Engine
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ReviewEngine>("Model.FK_reviews_review_engines", "review_engines").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ReviewEngine>("Model.FK_reviews_review_engines", "review_engines").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Engine in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<ReviewEngine> EngineReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ReviewEngine>("Model.FK_reviews_review_engines", "review_engines");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<ReviewEngine>("Model.FK_reviews_review_engines", "review_engines", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Model.SearchEngine in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Model", Name="SearchEngine")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class SearchEngine : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new SearchEngine object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="description">Initial value of Description.</param>
        public static SearchEngine CreateSearchEngine(int id, string name, string description)
        {
            SearchEngine searchEngine = new SearchEngine();
            searchEngine.Id = id;
            searchEngine.Name = name;
            searchEngine.Description = description;
            return searchEngine;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Media in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Model", "FK_media_search_engines", "media")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Media> Media
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Media>("Model.FK_media_search_engines", "media");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Media>("Model.FK_media_search_engines", "media", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Model.User in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Model", Name="User")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class User : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="firstName">Initial value of FirstName.</param>
        /// <param name="lastName">Initial value of LastName.</param>
        public static User CreateUser(int id, string firstName, string lastName)
        {
            User user = new User();
            user.Id = id;
            user.FirstName = firstName;
            user.LastName = lastName;
            return user;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this.ReportPropertyChanging("FirstName");
                this._FirstName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("FirstName");
                this.OnFirstNameChanged();
            }
        }
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this.ReportPropertyChanging("LastName");
                this._LastName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("LastName");
                this.OnLastNameChanged();
            }
        }
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for LoginId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Model", "FK_login_users", "login")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public LoginIdentification LoginId
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<LoginIdentification>("Model.FK_login_users", "login").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<LoginIdentification>("Model.FK_login_users", "login").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for LoginId in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<LoginIdentification> LoginIdReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<LoginIdentification>("Model.FK_login_users", "login");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<LoginIdentification>("Model.FK_login_users", "login", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Media in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Model", "FK_users_media_users", "users_media")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<UsersMedia> Media
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<UsersMedia>("Model.FK_users_media_users", "users_media");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<UsersMedia>("Model.FK_users_media_users", "users_media", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Model.UsersMedia in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Model", Name="UsersMedia")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class UsersMedia : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new UsersMedia object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        public static UsersMedia CreateUsersMedia(int id)
        {
            UsersMedia usersMedia = new UsersMedia();
            usersMedia.Id = id;
            return usersMedia;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Media in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Model", "FK_users_media_media", "media")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Media Media
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Media>("Model.FK_users_media_media", "media").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Media>("Model.FK_users_media_media", "media").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Media in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Media> MediaReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Media>("Model.FK_users_media_media", "media");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Media>("Model.FK_users_media_media", "media", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Model", "FK_users_media_users", "users")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public User User
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("Model.FK_users_media_users", "users").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("Model.FK_users_media_users", "users").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<User> UserReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("Model.FK_users_media_users", "users");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<User>("Model.FK_users_media_users", "users", value);
                }
            }
        }
    }
}
